[submodule "cmangos"]
    path = cmangos
    url = https://github.com/cmangos/mangos-tbc.git
[submodule "acid"]
    path = acid
    url = https://github.com/ACID-Scripts/TBC.git
[submodule "tbcdb"]
    path = tbcdb
    url = https://github.com/TBC-DB/Database.git
[submodule "eluna"]
	path = eluna
	url = https://github.com/ElunaLuaEngine/ElunaMangosTbc.git
[submodule "docker/volumes/eluna-scripts"]
	path = docker/volumes/eluna-scripts
	url = https://github.com/sattelite/ElunaScripts.git
