version: '2'
services:

  ## Database
  percona:
    image: percona:latest
    volumes:
    - ./volumes/percona/data:/var/lib/mysql

  ## cMaNGOS
  mangosd:
    image: mangosd:latest
    links:
    - percona
    volumes:
    - ../data:/opt/data
    - ./volumes/cmangos:/opt/cmangos

  realmd:
    image: cmangos:latest
    links:
    - percona
    volumes:
    - ./volumes/cmangos:/opt/cmangos


# vim:set et sw=2 sts=2:
